POSITIVE_WORDS = {
    "상승",
    "반등",
    "호재",
    "강세",
    "회복",
    "매수",
    "급등",
    "폭등",
    "오르",
    "떡상",
    "간다",
    "돌파",
    "좋",
    "기대",
    "휴전",
    "완화",
    "개선세",
    "회담",
    "합의",
    "bullish",
    "rally",
    "beat",
    "surge",
    "gain",
}

NEGATIVE_WORDS = {
    "하락",
    "급락",
    "악재",
    "약세",
    "붕괴",
    "공포",
    "불안",
    "매도",
    "떨어",
    "내리",
    "손절",
    "망했",
    "망해",
    "끝났",
    "위기",
    "전쟁",
    "공격",
    "포격",
    "폭격",
    "중단",
    "봉쇄",
    "거품",
    "무섭",
    "답없",
    "bearish",
    "crash",
    "drop",
    "miss",
}

INTENSIFIERS = {"매우", "진짜", "완전", "너무", "엄청", "really", "very", "super"}
NEGATIONS = {"안", "못", "없", "아니", "not", "never", "no"}

FEAR_WORDS = {
    "공포",
    "불안",
    "패닉",
    "하락",
    "급락",
    "폭락",
    "붕괴",
    "리스크",
    "위기",
    "손절",
    "떨어",
    "전쟁",
    "공격",
    "포격",
    "폭격",
    "봉쇄",
    "중단",
    "휴전",
    "무섭",
    "불길",
    "호르무즈",
    "panic",
    "fear",
    "risk",
    "crash",
}

GREED_WORDS = {
    "탐욕",
    "상승",
    "급등",
    "폭등",
    "랠리",
    "호재",
    "풀매수",
    "떡상",
    "greed",
    "moon",
    "pump",
    "rally",
    "breakout",
    "거품",
}

UNCERTAINTY_WORDS = {
    "불확실",
    "애매",
    "관망",
    "추정",
    "가능성",
    "우려",
    "의문",
    "모름",
    "헷갈",
    "maybe",
    "uncertain",
    "possibly",
    "likely",
    "unclear",
}

HATE_OR_AGGRESSION_WORDS = {
    "혐오",
    "증오",
    "역겹",
    "소름",
    "꺼져",
    "죽어",
    "씨발",
    "씨빨",
    "병신",
    "좆",
    "개추",
    "쓰레기",
    "패버",
    "멸망",
    "혐",
    "hate",
    "disgust",
    "trash",
    "idiot",
    "stupid",
}

TAG_KEYWORDS = {
    "주가": {"상승", "하락", "급등", "급락", "반등", "랠리", "주가", "price", "stock"},
    "변동성": {"공포", "탐욕", "패닉", "변동성", "vix", "risk", "panic", "volatility"},
    "실적": {"실적", "매출", "영업이익", "가이던스", "earnings", "revenue", "guidance"},
    "반도체": {"반도체", "엔비디아", "삼성전자", "sk하이닉스", "semiconductor", "gpu", "chip"},
    "AI": {"ai", "인공지능", "llm", "gpu", "openai"},
    "금리": {"금리", "fed", "fomc", "파월", "rate", "rates"},
    "환율": {"환율", "달러", "원화", "엔화", "usdkrw", "fx"},
    "정책": {"정책", "관세", "규제", "정부", "법안", "policy", "tariff", "regulation"},
    "암호화폐": {"비트코인", "이더리움", "코인", "crypto", "bitcoin", "ethereum"},
    "개미심리": {"개미", "손절", "물타기", "풀매수", "fomo", "bagholder"},
    "커뮤니티반응": {"혐오", "증오", "역겹", "쓰레기", "병신", "씨발", "망해", "조롱"},
    "전쟁리스크": {"전쟁", "포격", "폭격", "공격", "휴전", "중단", "봉쇄", "호르무즈", "이란"},
    "원유": {"유가", "원유", "석유", "비축유", "opec", "wti"},
}

TOPIC_KEYWORDS = {
    "rates": {"금리", "fed", "fomc", "rate", "rates", "파월"},
    "inflation": {"cpi", "ppi", "inflation", "물가", "인플레이션"},
    "fx": {"환율", "달러", "원화", "usdkrw", "fx"},
    "semiconductor": {"반도체", "엔비디아", "삼성전자", "sk하이닉스", "gpu", "chip"},
    "ai": {"ai", "인공지능", "llm", "gpu"},
    "us_equity": {"나스닥", "s&p500", "다우", "미장", "미국주식", "nasdaq"},
    "kr_equity": {"코스피", "코스닥", "국장", "한국주식", "kospi", "kosdaq"},
    "crypto": {"비트코인", "이더리움", "코인", "bitcoin", "ethereum", "crypto"},
    "oil": {"유가", "원유", "석유", "비축유", "wti", "opec"},
    "geopolitics": {"전쟁", "공격", "포격", "폭격", "휴전", "이란", "호르무즈", "봉쇄"},
}

ENTITY_PATTERNS = {
    "company": {"엔비디아", "테슬라", "삼성전자", "sk하이닉스", "애플", "microsoft", "nvidia", "tesla"},
    "index": {"s&p500", "나스닥", "다우", "코스피", "코스닥", "vix", "nasdaq", "kospi"},
    "indicator": {"cpi", "ppi", "gdp", "실업률", "금리", "환율", "inflation"},
    "country": {"미국", "한국", "중국", "일본", "유럽", "usa", "korea", "china", "japan"},
}

STOPWORDS = {
    "그리고",
    "하지만",
    "그냥",
    "이건",
    "저건",
    "진짜",
    "너무",
    "오늘",
    "내일",
    "시장",
    "경제",
    "주식",
    "stock",
    "market",
    "today",
    "really",
    "very",
    "that",
    "this",
    "with",
}
